version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: racing-car
    container_name: racing-car-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - project:/var/www
  
  files:
    image: alpine:latest
    container_name: racing-car-files
    entrypoint: top
    restart: unless-stopped
    volumes:
      - project:/project

volumes:
  project: