version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ice-cream-scorer
    container_name: ice-cream-scorer-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - project:/var/www

  files:
    image: alpine:latest
    container_name: ice-cream-scorer-files
    entrypoint: top
    restart: unless-stopped
    volumes:
      - project:/project

volumes:
  project:
